### ISSUE TITLE
Implement Processing Workflow

### ISSUE THREAD

**Issue by dixonwhitmire** [LinuxForHealth/pyconnect#51]
Implement a processing workflow to support uniform processing across data routes. At a high level the workflow will support the following "logical" steps. The route will determine which steps are required

- Data Validation
- Data Persistence
- Data Transformation
- Data Transmission
- Exception Handling

Data validation is used to validate data in it's original "native" format.
The data persistence step saves the data payload in the LinuxForHealth data store.
Data transform may be used to transform the data payload into an appropriate format for an external system.
Data transmission submits the data payload to one or more external systems.
Exception Handling  is a cross-cutting concern which logs and "handles" errors throughout the process.

Some options to consider:

Data Validation, Data Persistence, and Data Transformation could be defined within the core python code base, with Data Transmission and Exception Handling implemented using NATS messaging
OR
NATS could be used for routing, where each step in the workflow is a "topic"

**Comment by dixonwhitmire** [comment]
Ted would like us to use NATS to implement "the route".
This would mean that we would define "route metadata" (NATS topics) in python which would then traverse the appropriate "subjects".
Example
```
FHIR R4 Route
Subjects: Validate, Persistence, Transform, Transmit
```

**Comment by ccorley** [comment]
Duplicate of #8
