### ISSUE TITLE
Create Initial Project Structure

### ISSUE THREAD

**Issue by dixonwhitmire** [LinuxForHealth/pyconnect#53]
Create the initial structure for the project including a setup.py with minimal dependencies for:

- pytest
- NATS messaging
- Kafka Client
- Requests

**Comment by dixonwhitmire** [comment]
We will also include:

- The"container-support" assets from "Java" LinuxForHealth connect
- A containerized [FTP Server](https://github.com/giampaolo/pyftpdlib)

**Comment by ccorley** [comment]
Closing, as it contains more commits than intended.
