### ISSUE TITLE
Implement/Migrating Imaging Server Route

### ISSUE THREAD

**Issue by dixonwhitmire** [LinuxForHealth/pyconnect#79]
Determine if we will utilize the Orthanc imaging server in pyConnect or an alternative. If we will utilize Orthanc we can migrate the existing route from the Java connect application, otherwise we can implement a new route for an imaging server.

**Comment by cdanup1** [comment]
References:
- https://www.confluent.io/blog/how-to-prepare-for-kip-500-kafka-zookeeper-removal-guide/
- https://www.confluent.io/blog/42-ways-zookeeper-removal-improves-kafka/

**Comment by dixonwhitmire** [comment]
Closing as will resume tracking with ZenHub once pyConnect is public
